project1:
  faceBook:
    - 1_intro.yaml 
    - 2_context.yaml
    - 3_tool_constrainst.yaml
    - 4_output_structure.yaml
    - 5_post_validation.yaml
    - 6_final_reminder.yaml 
  JD_Creation:
    - 1_intro.yaml
    - 2_context.yaml
    - 3_tool_constrainst.yaml
    - 4_output_structure.yaml
    - 5_post_validation.yaml
    - 6_final_reminder.yaml
  Content_Creation:
    - classification_intro.yml
    - classification_rules.yml

project2:
  chatbot:
    - chatbot_greeting.yml
    - chatbot_qa.yml

